### ISSUE TITLE
Elligible API not working

### ISSUE THREAD

**Issue by Jo-ravar** [Ravi-Joshi-22/Major-Project#63]
### Issue Description

- `Get total experience` is not working or is not properly handled.

### Related Screenshots:
![elligible bug](https://user-images.githubusercontent.com/20628218/36393763-f6f6b37e-15d6-11e8-9dea-d0de7bc6a6f8.PNG)

**Comment by sanyog96** [comment]
Bug fixed

**Comment by Jo-ravar** [comment]
This is fixed now
